server:
  port: 9004
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
spring:
  application:
    name: goods
  datasource:
    name: goods_datasource
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shop_goods
    username: root
    password: admin
mybatis:
  type-aliases-package: com.patriotdevelopment.mapper
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml