server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
spring:
  application:
    name: order
  datasource:
    name: order_datasource
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shop_order
    username: root
    password: admin
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
mybatis:
  type-aliases-package: com.patriotdevelopment.mapper
  mapper-locations: classpath:mapping/*.xml
  config-location: classpath:mybatis-config.xml